config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cars#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  resources :cars do
   resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy]


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_at, :end_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  validates :model, :brand, :year, :color, :km, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :cars , through: :booking
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController

  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
   before_action :set_car, only: [:show, :destroy, :update, :edit]

  def index
    @cars = Car.all

  end

  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end
  def destroy

  end

  private

  def car_params
     params.require(:car).permit(:model, :brand, :year, :km, :color, :image)
  end

  def set_car
     @car = car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<section class="header">
  <div class="logo">
    <h1>LOUER VOTRE VOITURE</h1>
    <h2>à des prix diaboliques</h2>
  </div>
</section>
<section class="list-cars">
  <div class="container">
    <div class="cards">
      <% @cars.each do |car| %>
        <%= link_to car_path(car), class:"card" do %>
          <div class="card_image">
            <%= image_tag("porsche.webp") %>
          </div>
          <div class="card-content">
            <p><%= car.model %></p>
            <p><%= car.brand %></p>
            <p><%= car.color %></p>
            <p><%= car.year %></p>
            <p><%= car.km %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTraining</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>